# Generated by Django 3.2.16 on 2024-07-24 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0005_auto_20240724_1816'),
    ]

    operations = [
        migrations.RenameField(
            model_name='birthday',
            old_name='tag',
            new_name='tags',
        ),
    ]
