# Generated by Django 3.2.16 on 2024-07-04 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ice_cream', '0003_auto_20240704_1014'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='icecream',
            options={'ordering': ('output_order', 'title'), 'verbose_name': 'мороженое', 'verbose_name_plural': 'мороженое'},
        ),
        migrations.RenameField(
            model_name='icecream',
            old_name='output_oreder',
            new_name='output_order',
        ),
    ]
